### ISSUE TITLE
Price check on belt with +2 charm slots does not appear in appraisal screen

### ISSUE THREAD

**Issue by mirarix** [Eclipseop/gage-trade#53]
When price checking (ctrl+d) a belt with the "+2 Charm Slots" modifier, it does not appear in the list of modifiers you can select. 
See attached!

![image](https://github.com/user-attachments/assets/4a4fba13-112b-4b49-b427-0536f5ef6e19)

The item's CTRL+C is below:

```
Item Class: Belts
Rarity: Rare
Beast Shackle
Long Belt
--------
Charm Slots: 3 (augmented)
--------
Requirements:
Level: 54
--------
Item Level: 80
--------
15% increased Charm Effect Duration (implicit)
--------
+161 to maximum Life
+16 to maximum Mana
+2 Charm Slots
+19% to Cold Resistance
19.7 Life Regeneration per second
4 to 7 Physical Thorns damage
```

Thanks!

**Comment by Eclipseop** [comment]
Fixed in upcoming release
